### ISSUE TITLE
Design user interface

### ISSUE THREAD

**Issue by JaredButcher** [KentStateRobotics/Control3#5]
Design the graphical user interface's layout and workflow. Needs to plan for at least telemetry, video feed, simulated environment, controls, e-stop, autonomy, partial autonomy. Should be approved by the team before implemented.

**Comment by sh30801** [comment]
When should we start working on the layout/design?

**Comment by JaredButcher** [comment]
As soon as possible. By designing the layout we would have a good starting point for implementing the features shown in the UI. Just remember to stay flexible with the design because it will change for one reason or another.

**Comment by sh30801** [comment]
For sure. I'll get started working on the backend of it then
